---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: jellyfin-restore
  namespace: jellyfin
spec:
  trigger:
    manual: restore-once
  restic:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheStorageClassName: openebs-hostpath
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    repository: jellyfin-r2-secret
    copyMethod: Snapshot
    destinationPVC: jellyfin-config
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
