---
controllers:
  amd-device-plugin:
    type: daemonset

    containers:
      app:
        image:
          repository: docker.io/rocm/k8s-device-plugin
          tag: 1.31.0.11@sha256:e4df5dc9a7fa34e2344852256dcc5762171a6d68f1f9a34026ce26786ae335e2

        workingDir: /root

        command: ["./k8s-device-plugin"]

        args: ["-logtostderr=true", "-stderrthreshold=INFO", "-v=5"]

        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            memory: 100Mi

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

service:
  app:
    enabled: false
    controller: amd-device-plugin

persistence:
  sys:
    enabled: true
    type: hostPath
    hostPath: /sys

  device-plugins:
    enabled: true
    type: hostPath
    hostPath: /var/lib/kubelet/device-plugins
