githubConfigSecret: "github-pat"
githubConfigUrl: "https://github.com/guilhermewolf/atoca.house"
controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

maxRunners: 3
minRunners: 1

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/home-operations/actions-runner:2.335.1@sha256:3d544e5eed58722c0b6a97212a31eada0f9f2e99f189c41911a5573a23d7386a
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        envFrom:
          - secretRef:
              name: postgres-pguser-terraform
metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"
