githubConfigSecret: "github-pat"
githubConfigUrl: "https://github.com/guilhermewolf/atoca.house"
controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

maxRunners: 3
minRunners: 1

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/home-operations/actions-runner:2.336.0@sha256:281a9a090522fafbf4967f158b8c97d03552b1978b688893c5f7cb1944bc5fe5
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        envFrom:
          - secretRef:
              name: postgres-pguser-terraform
metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"
