githubConfigSecret: "github-pat"
githubConfigUrl: "https://github.com/guilhermewolf/atoca.house"
controllerServiceAccount:
  namespace: arc-systems
  name: arc-systems-gha-rs-controller

maxRunners: 3
minRunners: 1

template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/home-operations/actions-runner:2.332.0@sha256:577ec3d514700203d07a8b14ac9238e2c8bf7565969f9d3bddf5dac1c60c43b7
        command: ["/home/runner/run.sh"]
        env:
          - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
            value: "false"
          - name: NODE
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        envFrom:
          - secretRef:
              name: postgres-pguser-terraform
metrics:
  controllerManagerAddr: ":8080"
  listenerAddr: ":8080"
  listenerEndpoint: "/metrics"
