app:
  name: rook-ceph-csi-drivers
  namespace: rook-ceph
  chart: ceph-csi-drivers
  chartRepo: https://ceph.github.io/ceph-csi-operator
  chartVersion: 1.0.1
  disableAutoSync: true
  podSecurityPrivileged: true
