---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-secret
  namespace: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: postiz-secret
    template:
      data:
        JWT_SECRET: "{{ .JWT_SECRET }}"
        INSTAGRAM_APP_ID: "{{ .INSTAGRAM_APP_ID }}"
        INSTAGRAM_APP_SECRET: "{{ .INSTAGRAM_APP_SECRET }}"
  dataFrom:
    - extract:
        key: postiz-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postiz-db-secret
  namespace: postiz
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: postiz-db-secret
    template:
      data:
        # Database Configuration
        DATABASE_URL: 'postgres://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" | toString }}/{{ index . "dbname" }}?sslmode=prefer'
  dataFrom:
    - extract:
        key: postgres-pguser-postiz
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
