---
connect:
  api:
    httpPort: 80
    imageRepository: ghcr.io/1password/connect-api
    serviceMonitor:
      enabled: true
  credentialsName: onepassword-connect-credentials-secret
  sync:
    imageRepository: ghcr.io/1password/connect-sync
