---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name atuin-db-secret
  namespace: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        ATUIN_DB_URI: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-atuin
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
