---
controllers:
  atuin:
    containers:
      app:
        image:
          repository: ghcr.io/atuinsh/atuin
          tag: 18.21.0@sha256:38c6c323c6d3864250dc345dcf9d41b7a408ee6e33a7cc3cde44b6ffe9f64a02
        env:
          ATUIN_HOST: "0.0.0.0"
          ATUIN_PORT: &port 80
          ATUIN_OPEN_REGISTRATION: "true"
        envFrom:
          - secretRef:
              name: atuin-db-secret
        args:
          - start
        probes:
          liveness:
            enabled: true
            spec:
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: *port
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 256Mi
defaultPodOptions:
  annotations:
    k8s.ksgate.org/postgres-ready: |
      {
        "apiVersion": "postgres-operator.crunchydata.com/v1beta1",
        "kind": "PostgresCluster",
        "name": "postgres",
        "namespace": "crunchy-postgres-cluster",
        "expression": "has(resource.status.instances) && resource.status.instances.exists(i, i.readyReplicas >= 1)"
      }
    k8s.ksgate.org/postgres-service: |
      {
        "apiVersion": "v1",
        "kind": "Service",
        "name": "postgres-pgbouncer",
        "namespace": "crunchy-postgres-cluster"
      }
  schedulingGates:
    - name: k8s.ksgate.org/postgres-ready
    - name: k8s.ksgate.org/postgres-service
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    ports:
      http:
        port: *port

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - "atuin.atoca.house"
    rules:
      - backendRefs:
          - name: atuin
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config
