---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwa-secret
  namespace: openwa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        API_MASTER_KEY: "{{ .API_MASTER_KEY }}"
  dataFrom:
    - extract:
        key: openwa-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwa-db-secret
  namespace: openwa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: openwa-db-secret
    template:
      data:
        DATABASE_NAME: '{{ index . "dbname" }}'
        DATABASE_HOST: '{{ index . "host" }}'
        DATABASE_PORT: '{{ index . "port" }}'
        DATABASE_USERNAME: '{{ index . "user" }}'
        DATABASE_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-openwa
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwa-r2-secret
  namespace: openwa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .RESTIC_REPOSITORY }}/openwa"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-r2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
