---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      data:
        nextcloud-username: "{{ .NEXTCLOUD_USERNAME }}"
        nextcloud-password: "{{ .NEXTCLOUD_PASSWORD }}"
  dataFrom:
    - extract:
        key: nextcloud-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
