---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: hermes-kf-restore
  namespace: hermes-kf
spec:
  trigger:
    manual: restore-once
  restic:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheStorageClassName: openebs-hostpath
    cleanupCachePVC: true
    cleanupTempPVC: true
    enableFileDeletion: true
    repository: hermes-kf-r2-secret
    copyMethod: Snapshot
    destinationPVC: hermes-kf
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 10000
      runAsGroup: 10000
      fsGroup: 10000
