---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-kf-secret
  namespace: hermes-kf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hermes-kf-secret
    template:
      data:
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        LITELLM_MASTER_KEY: "{{ .LITELLM_MASTER_KEY }}"
        HERMES_DASHBOARD_BASIC_AUTH_USERNAME: "{{ .HERMES_DASHBOARD_BASIC_AUTH_USERNAME }}"
        HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: "{{ .HERMES_DASHBOARD_BASIC_AUTH_PASSWORD }}"
        N8N_API_KEY: "{{ .N8N_API_KEY }}"
        OUTLINE_API_KEY: "{{ .OUTLINE_API_KEY }}"
        WIKI_API_KEY: "{{ .WIKI_API_KEY }}"
        POSTIZ_API_KEY: "{{ .POSTIZ_API_KEY }}"
        OPUS_API_KEY: "{{ .OPUS_API_KEY }}"
        GROUP_ID: "{{ .GROUP_ID }}"
        WHATSAPP_ALLOWED_USERS: "{{ .WHATSAPP_ALLOWED_USERS }}"
  dataFrom:
    - extract:
        key: hermes-kf-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: litellm-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
