apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gluetun-credentials
  namespace: vpn-gateway
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gluetun-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
  data:
    - secretKey: username
      remoteRef:
        key: gluetun-pia-vpn
        property: username
    - secretKey: password
      remoteRef:
        key: gluetun-pia-vpn
        property: password
