---
# Application configuration for speedtest-exporter-lan
app:
  name: speedtest-exporter-lan
  namespace: speedtest-exporter-lan
  chart: speedtest-exporter-lan
  chartRepo: gsoci.azurecr.io/charts/giantswarm
  chartVersion: 0.20.1
  useVaultPlugin: false
