---
# Application configuration for speedtest-exporter-lan
app:
  name: speedtest-exporter-lan
  namespace: speedtest-exporter-lan
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 5.0.1
  useVaultPlugin: false
