---
controllers:
  local-ai:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: quay.io/go-skynet/local-ai
          tag: v3.12.1-gpu-nvidia-cuda-12@sha256:7067ca72d4c21af16d6b6aeba257ede289eaf3a82006c55a27887eeb711603c9
        args:
          - "run"
          - "--enable-memory-reclaimer"
          - "--memory-reclaimer-threshold=0.8"
          - "--enable-watchdog-idle"
          - "--watchdog-idle-timeout=15m"
        env:
          LOCALAI_MODELS_PATH: /models
          LOCALAI_EXTERNAL_BACKENDS: "llama-cpp"
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: compute,utility
          DEBUG: "true"
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /readyz
                port: 8080
              initialDelaySeconds: 300
              periodSeconds: 30
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /readyz
                port: 8080
              initialDelaySeconds: 120
              periodSeconds: 15
        resources:
          requests:
            cpu: 500m
            #memory: 4Gi
            nvidia.com/gpu: 1
          limits:
            #memory: 16Gi
            nvidia.com/gpu: 1
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: { drop: ["ALL"] }

defaultPodOptions:
  runtimeClassName: nvidia
  nodeSelector:
    node.kubernetes.io/gpu: "true"
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }

service:
  app:
    controller: local-ai
    ports:
      http:
        port: 8080

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - local-ai.atoca.house
    rules:
      - backendRefs:
          - name: local-ai
            port: 8080
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  models:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /models
  # config:
  #   type: configMap
  #   name: local-ai-config-nvidia
  #   globalMounts:
  #     - path: /models/qwen2.5-coder-7b.yaml
  #       subPath: qwen2.5-coder-7b.yaml
  #     - path: /models/qwen2.5-coder-14b.yaml
  #       subPath: qwen2.5-coder-14b.yaml
  backends:
    type: emptyDir
    globalMounts:
      - path: /backends
