---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/litellm.home-operations.com/litellmmodel_v1alpha1.json
apiVersion: litellm.home-operations.com/v1alpha1
kind: LiteLLMModel
metadata:
  name: gemma4-12b
spec:
  modelName: gemma4-12b
  params:
    model: ollama_chat/gemma4:12b
    apiBase: http://ollama.ollama.svc.cluster.local
  info:
    maxInputTokens: 15000
