---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spoolman-db-secrets
  namespace: spoolman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: spoolman-db-secrets
    template:
      engineVersion: v2
      data:
        SPOOLMAN_DB_USERNAME: '{{ index . "user" }}'
        SPOOLMAN_DB_PASSWORD: '{{ index . "password" }}'
        SPOOLMAN_DB_HOST: '{{ index . "host" }}'
        SPOOLMAN_DB_PORT: '{{ index . "port" }}'
        SPOOLMAN_DB_NAME: '{{ index . "dbname" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-spoolman
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
