app:
  name: cilium
  namespace: kube-system
  chart: cilium
  chartRepo: https://helm.cilium.io/
  chartVersion: 1.19.4 # renovate: datasource=helm depName=cilium registryUrl=https://helm.cilium.io

  customIgnoreDifferences: true
  disableAutoSync: true
