---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mediamtx-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mediamtx-secret
    template:
      data:
        MTX_AUTHINTERNALUSERS_0_USER: "{{ .OBS_PUBLISH_USER }}"
        MTX_AUTHINTERNALUSERS_0_PASS: "{{ .OBS_PUBLISH_PASSWORD }}"
        TWITCH_STREAM_KEY: "{{ .TWITCH_STREAM_KEY }}"
        MTX_AUTHINTERNALUSERS_3_USER: "{{ .API_USER }}"
        MTX_AUTHINTERNALUSERS_3_PASS: "{{ .API_PASSWORD }}"
  dataFrom:
    - extract:
        key: mediamtx-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
