---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: kavita-restore
  namespace: kavita
spec:
  trigger:
    manual: restore-once
  restic:
    repository: kavita-r2-secret
    copyMethod: Direct
    destinationPVC: kavita
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
