---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: karakeep
  namespace: karakeep
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: karakeep
    template:
      data:
        # App
        NEXTAUTH_SECRET: "{{ .KARAKEEP_NEXTAUTH_SECRET }}"
        MEILI_MASTER_KEY: "{{ .KARAKEEP_MEILI_MASTER_KEY }}"
        # OIDC (must match Authelia client_secret plaintext)
        OAUTH_CLIENT_SECRET: "{{ .KARAKEEP_OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: karakeep-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: authelia
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
