---
controllers:
  it-tools:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/home-operations/it-tools
          tag: 2024.10.22@sha256:7f26ae8d7a4a58b8d70b685cba5cbaa54d7df876d9f8bae702207f45b06d9b7c
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 5m
            memory: 50Mi
          limits:
            memory: 250Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    ports:
      http:
        port: 8080
route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - it-tools.atoca.house
    rules:
      - backendRefs:
          - name: it-tools
            port: 8080
        matches:
          - path:
              type: PathPrefix
              value: /
persistence:
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /tmp
