---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-secrets
  namespace: rustfs
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: rustfs-secrets
    template:
      data:
        RUSTFS_ACCESS_KEY: "{{ .RUSTFS_ACCESS_KEY }}"
        RUSTFS_SECRET_KEY: "{{ .RUSTFS_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: rustfs-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
