---
controllers:
  rustfs:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: rustfs/rustfs
          tag: 1.0.0-alpha.85@sha256:23ff2af1ec2d64e0fb9608a1c39b5eb96fcff3a8efecf332986c948b0e3e4f8a
        env:
          RUSTFS_SERVER_DOMAINS: s3.atoca.house,rustfs.atoca.house
          RUSTFS_CONSOLE_ENABLE: true
        envFrom:
          - secretRef:
              name: rustfs-secrets
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: [ALL] }
        resources:
          requests:
            cpu: 100m
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch
    seccompProfile: { type: RuntimeDefault }

service:
  app:
    ports:
      s3:
        port: &port 9000
      portal:
        port: 9001

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - s3.atoca.house
    rules:
      - backendRefs:
          - name: rustfs
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
  portal:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - rustfs.atoca.house
    rules:
      - backendRefs:
          - name: rustfs
            port: 9001
        matches:
          - path:
              type: PathPrefix
              value: /
persistence:
  data:
    type: nfs
    server: nas.internal
    path: /mnt/user/rustfs/data
    globalMounts:
      - path: /data
  logs:
    type: emptyDir
    globalMounts:
      - path: /logs
