---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-secrets
  namespace: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crowdsec-secrets
    template:
      data:
        CROWDSEC_LAPI_SECRET: "{{ .CROWDSEC_LAPI_SECRET }}"
        ENROLL_KEY: "{{ .ENROLL_KEY }}"
        REGISTRATION_TOKEN: "{{ .REGISTRATION_TOKEN }}"
        BOUNCER_KEY_envoy_bouncer: "{{ .ENVOY_BOUNCER_BOUNCER_APIKEY }}"
        BOUNCER_KEY_envoy_bouncer_waf: "{{ .ENVOY_BOUNCER_WAF_APIKEY }}"
  dataFrom:
    - extract:
        key: crowdsec-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - extract:
        key: envoy-bouncer-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-db-secrets
  namespace: crowdsec
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: crowdsec-db-secrets
    template:
      data:
        # Database Configuration
        DB_HOST: '{{ index . "host" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_PASSWORD: '{{ index . "password" }}'
        DB_USERNAME: '{{ index . "user" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-crowdsec
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
