---
podAnnotations:
  reloader.stakater.com/auto: "true"
container_runtime: containerd
config:
  parsers:
    s01-parse:
      envoy-logs.yaml: |-
        filter: "evt.Parsed.program startsWith 'envoy' && evt.Parsed.message contains ':authority'"
        onsuccess: next_stage
        name: hydaz/envoy-logs
        description: "Parse Envoy access logs to match nginx parser outputs"
        statics:
          - parsed: json
            expression: UnmarshalJSON(evt.Parsed.message, evt.Unmarshaled, "envoy")
          - parsed: time_local
            expression: evt.Unmarshaled.envoy["start_time"]
          - parsed: remote_addr
            expression: Split(evt.Unmarshaled.envoy["x-forwarded-for"], ",")[0]
          - parsed: verb
            expression: evt.Unmarshaled.envoy["method"]
          - parsed: request
            expression: evt.Unmarshaled.envoy["x-envoy-origin-path"]
          - parsed: http_version
            expression: TrimPrefix(evt.Unmarshaled.envoy["protocol"], "HTTP/")
          - parsed: status
            expression: Sprintf('%.0f', evt.Unmarshaled.envoy["response_code"])
          - parsed: body_bytes_sent
            expression: Sprintf('%.0f', evt.Unmarshaled.envoy["bytes_sent"])
          - parsed: http_user_agent
            expression: evt.Unmarshaled.envoy["user-agent"]
          - parsed: target_fqdn
            expression: evt.Unmarshaled.envoy[":authority"]
          - meta: service
            value: http
          - meta: log_type
            value: http_access-log
          - meta: source_ip
            expression: evt.Parsed.remote_addr
          - meta: http_status
            expression: evt.Parsed.status
          - meta: http_path
            expression: evt.Parsed.request
          - meta: http_verb
            expression: evt.Parsed.verb
          - meta: http_user_agent
            expression: evt.Parsed.http_user_agent
          - meta: target_fqdn
            expression: evt.Parsed.target_fqdn
    s02-enrich:
      envoy-418-whitelist.yaml: |-
        name: hydaz/envoy-418-whitelist
        description: "Whitelist 418 responses from the envoy bouncer to prevent processing already banned IPs"
        filter: "evt.Meta.service == 'http' && evt.Meta.log_type == 'http_access-log'"
        whitelist:
          reason: "envoy bouncer response to already banned ips"
          expression:
            - "evt.Meta.http_status == '418'"
  config.yaml.local: |-
    api:
      server:
        auto_registration:
          enabled: true
          token: ${REGISTRATION_TOKEN}
          allowed_ranges:
            - 10.244.0.0/16
  agent_config.yaml.local: |-
    api:
      client:
        unregister_on_exit: true
  appsec_config.yaml.local: |-
    api:
      client:
        unregister_on_exit: true
  profiles.yaml: |-
    name: default_ip_remediation
    debug: false
    filters:
      - Alert.Remediation == true && Alert.GetScope() == "Ip"
    decisions:
      - type: ban
        duration: 24h
    on_success: break
secrets:
  externalSecret:
    name: crowdsec-lapi-secrets
lapi:
  strategy:
    type: RollingUpdate
  env:
    - name: ENROLL_INSTANCE_NAME
      value: cluster
    - name: DB_TYPE
      value: postgresql
    - name: DB_PORT
      value: "5432"
  envFrom:
    - secretRef:
        name: crowdsec-secrets
    - secretRef:
        name: crowdsec-db-secrets
  persistentVolume:
    data:
      enabled: false
    config:
      enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
agent:
  acquisition:
    - namespace: kube-system
      podName: atoca-house-*
      program: envoy
      poll_without_inotify: true
  env:
    - name: COLLECTIONS
      value: >-
        crowdsecurity/base-http-scenarios
        crowdsecurity/http-cve
    - name: PARSERS
      value: crowdsecurity/cri-logs
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
appsec:
  enabled: true
  acquisitions:
    - source: appsec
      listen_addr: "0.0.0.0:7422"
      path: /
      appsec_config: crowdsecurity/virtual-patching
      labels:
        type: appsec
  env:
    - name: COLLECTIONS
      value: >-
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/appsec-generic-rules
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
