---
# Application configuration for speedtest-exporter-vpn
app:
  name: speedtest-exporter-vpn
  namespace: speedtest-exporter-vpn
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 5.0.1
  useVaultPlugin: false
