controllers:
  kromgo:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      kromgo:
        image:
          repository: ghcr.io/home-operations/kromgo
          tag: 0.16.1@sha256:ad39dd32da600ea261112e7a098345d474d48c997790b0373eb651c66e490844
        env:
          KROMGO_PROMETHEUS_URL: http://kube-prometheus-stack-moni-prometheus.monitoring.svc.cluster.local:9090
          KROMGO_SERVER_PORT: &port 8080
          KROMGO_METRICS_ENABLED: "false"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: *port
              periodSeconds: 10
          readiness:
            <<: *probes
            spec:
              httpGet:
                path: /readyz
                port: *port
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 64Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile: { type: RuntimeDefault }
service:
  kromgo:
    controller: kromgo
    ports:
      http:
        primary: true
        port: 80
        targetPort: *port
route:
  kromgo:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-external
        namespace: kube-system
    annotations:
      gatus.home-operations.com/endpoint: |-
        conditions: ["[STATUS] == 200"]
    hostnames:
      - kromgo.atoca.house
    rules:
      - backendRefs:
          - name: kromgo
            port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
persistence:
  config-file:
    type: configMap
    name: kromgo-configmap
    globalMounts:
      - path: /config/config.yaml
        subPath: config.yaml
        readOnly: true
