---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mem0-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mem0-secrets
    template:
      engineVersion: v2
      data:
        #OPENAI_API_KEY: "{{ .MEM0_API_KEY }}"
        # Qdrant
        QDRANT_URL: http://qdrant.qdrant.svc.cluster.local:6333
        QDRANT_API_KEY: "{{ .QDRANT_API_KEY }}"
  dataFrom:
    # - extract:
    #     key: mem0-secret
    #     conversionStrategy: Default
    #     decodingStrategy: None
    #     metadataPolicy: None

    - extract:
        key: qdrant-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
