apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arc-system

resources:
  - namespace.yaml
  - secrets.yaml
  
helmCharts:
  - name: actions-runner-controller
    repo: https://actions-runner-controller.github.io/actions-runner-controller
    namespace: arc-system
    releaseName: actions-runner-controller
    version: 0.21.0
    valuesFile: values.yaml


  # - name: gha-runner-scale-set
  #   repo: oci://ghcr.io/actions/actions-runner-controller
  #   namespace: arc-system
  #   releaseName: gha-runner-scale-set
  #   version: 0.9.1
