---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: affine-restore
  namespace: affine
spec:
  trigger:
    manual: restore-once
  restic:
    repository: affine-r2-secret
    copyMethod: Direct
    destinationPVC: affine
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
