---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: affine-secrets
    template:
      data:
        # Affine
        REDIS_SERVER_HOST: dragonfly.dragonfly-cluster.svc.cluster.local
        REDIS_SERVER_PORT: "6379"
        # OIDC Configuration
        OAUTH_OIDC_ISSUER: https://auth.atoca.house
        OAUTH_OIDC_CLIENT_ID: affine
        OAUTH_OIDC_CLIENT_SECRET: "{{ .AFFINE_OAUTH_CLIENT_SECRET }}"
        OAUTH_OIDC_SCOPE: "openid email profile offline_access"
        OAUTH_OIDC_CLAIM_MAP_ID: preferred_username
        OAUTH_OIDC_CLAIM_MAP_EMAIL: email
        # mail
        MAILER_HOST: "{{ .SMTP_ADDRESS }}"
        MAILER_PORT: "{{ .SMTP_PORT }}"
        MAILER_USER: "{{ .SMTP_USERNAME }}"
        MAILER_PASSWORD: "{{ .SMTP_PASSWORD }}"
        MAILER_SENDER: "Affine <{{ .SMTP_FROM }}>"
  dataFrom:
    - extract:
        key: authelia
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - extract:
        key: smtp-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-db-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: affine-db-secrets
    template:
      data:
        # Affine
        DATABASE_URL: 'postgres://{{ index . "user" }}:{{ index . "password" }}@{{ index . "host" }}:{{ index . "port" | toString }}/{{ index . "dbname" }}?sslmode=prefer&schema=affine'
  dataFrom:
    - extract:
        key: postgres-pguser-affine
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: affine-r2-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .RESTIC_REPOSITORY }}/affine"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-r2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
