---
# Application configuration for Dragonfly Operator
app:
  name: dragonfly-operator
  namespace: dragonfly-operator
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 5.0.1
