---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name donetick-secret
  namespace: donetick
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      data:
        DT_JWT_SECRET: "{{ .DONETICK_JWT_SECRET }}"
        DT_OAUTH2_CLIENT_SECRET: "{{ .DONETICK_OAUTH_CLIENT_SECRET }}"
        # Garage S3 credentials for the `donetick` bucket
        DT_STORAGE_ACCESS_KEY: "{{ .DONETICK_S3_ACCESS_KEY_ID }}"
        DT_STORAGE_SECRET_KEY: "{{ .DONETICK_S3_SECRET_ACCESS_KEY }}"
        # SMTP
        DT_EMAIL_HOST: "{{ .SMTP_ADDRESS }}"
        DT_EMAIL_PORT: "{{ .SMTP_PORT }}"
        DT_EMAIL_USER: "{{ .SMTP_USERNAME }}"
        DT_EMAIL_KEY: "{{ .SMTP_PASSWORD }}"
        DT_EMAIL_EMAIL: "{{ .SMTP_FROM }}"
  dataFrom:
    - extract:
        key: donetick-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: authelia
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: smtp-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-pguser-donetick
  namespace: donetick
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: donetick-db-secret
    template:
      data:
        DT_DATABASE_HOST: '{{ index . "pgbouncer-host" }}'
        DT_DATABASE_PORT: '{{ index . "pgbouncer-port" | toString }}'
        DT_DATABASE_NAME: '{{ index . "dbname" }}'
        DT_DATABASE_USER: '{{ index . "user" }}'
        DT_DATABASE_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-donetick
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
