controllers:
  flaresolverr:
    replicas: 1
    containers:
      flaresolverr:
        image:
          repository: flaresolverr/flaresolverr
          tag: v3.5.2@sha256:c80ae007ce2ccdcd217a12426e4f039ef763ff90738c808d38810c3e59323767
          pullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL
            value: "info"
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            memory: 1Gi

service:
  flaresolverr:
    controller: flaresolverr
    ports:
      http:
        primary: true
        port: 80
        targetPort: 8191
route:
  flaresolverr:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - flaresolverr.atoca.house
    rules:
      - backendRefs:
          - name: flaresolverr
            port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
