controllers:
  flaresolverr:
    replicas: 1
    containers:
      flaresolverr:
        image:
          repository: flaresolverr/flaresolverr
          tag: v3.5.0@sha256:139dfee1c6f89249c8d665d1333a42e8ec74ec0a86bc6bb1c8461e10d3a66a47
          pullPolicy: IfNotPresent
        env:
          - name: LOG_LEVEL
            value: "info"
        resources:
          requests:
            cpu: 10m
            memory: 150Mi
          limits:
            memory: 1Gi

service:
  flaresolverr:
    controller: flaresolverr
    ports:
      http:
        primary: true
        port: 80
        targetPort: 8191
route:
  flaresolverr:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - flaresolverr.atoca.house
    rules:
      - backendRefs:
          - name: flaresolverr
            port: 80
        matches:
          - path:
              type: PathPrefix
              value: /
