---
# Application configuration for Bitfocus Companion
app:
  name: companion
  namespace: companion
  chart: app-template
  chartRepo: ghcr.io/bjw-s-labs/helm
  chartVersion: 5.0.1
  volsyncPrivileged: true
