---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jellystat-secret
  namespace: jellystat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: jellystat-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Jellystat
        JWT_SECRET: "{{ .JWT_SECRET }}"

  dataFrom:
    - extract:
        key: jellystat-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-pguser-jellystat
  namespace: jellystat
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: jellystat-db-secret
    template:
      data:
        POSTGRES_DB: '{{ index . "dbname" }}'
        POSTGRES_IP: '{{ index . "host" }}'
        POSTGRES_USER: '{{ index . "user" }}'
        POSTGRES_PASSWORD: '{{ index . "password" }}'
        POSTGRES_PORT: "5432"
        PGSSLMODE: "no-verify"
  dataFrom:
    - extract:
        key: postgres-pguser-jellystat
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
