---
controllers:
  jellystat:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      app:
        image:
          repository: cyfershepard/jellystat
          tag: 1.1.10@sha256:bb7ebe42424dedeff52d8da4130232d67e3fdd6dc2dd4a66091e32ddd835ea42
        env:
          NODE_EXTRA_CA_CERTS: /etc/ssl/postgres/ca.crt
        envFrom:
          - secretRef:
              name: jellystat-secret
          - secretRef:
              name: jellystat-db-secret
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: { drop: [ "ALL" ] }
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
          limits:
            memory: 1000Mi
    pod:
      securityContext:
        seccompProfile: { type: RuntimeDefault }
persistence:
  postgres-ca:
    type: configMap
    name: postgres-ca
    globalMounts:
      - path: /etc/ssl/postgres/ca.crt
        subPath: ca.crt
        readOnly: true

service:
  app:
    controller: jellystat
    ports:
      http:
        port: &port 3000

route:
  jellystat:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - jellystat.atoca.house
    rules:
      - backendRefs:
          - name: jellystat
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /
