controllers:
  recyclarr:
    type: cronjob
    cronjob:
      schedule: 0 0 * * *
      backoffLimit: 0
      concurrencyPolicy: Forbid
      successfulJobsHistory: 1
      failedJobsHistory: 1
      ttlSecondsAfterFinished: 86400
    containers:
      recyclarr:
        image:
          repository: ghcr.io/recyclarr/recyclarr
          tag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
        envFrom:
          - secretRef:
              name: "recyclarr-secret"
        args:
          - sync
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
    pod:
      restartPolicy: Never
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /config/

  config-file:
    type: configMap
    name: "{{ .Release.Name }}-config"
    globalMounts:
      - path: /config/recyclarr.yml
        subPath: recyclarr.yml
  tmp:
    type: emptyDir
