---
controllers:
  unifi-toolkit:
    annotations:
      reloader.stakater.com/auto: "true"

    containers:
      app:
        image:
          repository: ghcr.io/crosstalk-solutions/unifi-toolkit
          tag: 1.11.3@sha256:c2f0de48c2c7963e0dc3a87c5a11de106e884eaccfa4ad00d1fa2a0fbec23189
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 192Mi

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    ports:
      http:
        port: 8000

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - ui-toolkit.atoca.house
    rules:
      - backendRefs:
          - name: unifi-toolkit
            port: 8000
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /app/data
  env:
    type: secret
    name: unifi-toolkit-secret
    globalMounts:
      - path: /app/.env
        subPath: .env
  tmp:
    type: emptyDir
    globalMounts:
      - path: /tmp
