---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-secret
  namespace: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    template:
      data:
        OAUTH_CLIENT_SECRET: "{{ .OPEN_WEBUI_OAUTH_CLIENT_SECRET  }}"
        QDRANT_API_KEY: "{{ .QDRANT_API_KEY }}"
        WEBUI_SECRET_KEY: "{{ .OPEN_WEBUI_SECRET_KEY }}"
  dataFrom:
    - extract:
        key: authelia
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: qdrant-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - extract:
        key: open-webui-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-db-secret
  namespace: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: open-webui-db-secret
    template:
      data:
        DATABASE_NAME: '{{ index . "dbname" }}'
        DATABASE_HOST: '{{ index . "host" }}'
        DATABASE_USER: '{{ index . "user" }}'
        DATABASE_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-open-webui
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui-r2-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        RESTIC_REPOSITORY: "s3:{{ .RESTIC_REPOSITORY }}/open-webui"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - extract:
        key: volsync-restic-r2
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
