---
controllers:
  booklore:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsNonRoot: true
        runAsUser: 99
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: OnRootMismatch
    initContainers:
      mariadb:
        image:
          repository: docker.io/library/mariadb
          tag: 12.2.2-noble
        env:
          MARIADB_DATABASE: booklore
          MARIADB_USER: booklore
          PGID: 1000
          PUID: 1000
        envFrom:
          - secretRef:
              name: mariadb-secret
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              exec:
                command:
                  - bash
                  - -c
                  - |-
                    mariadb-admin ping --socket=/run/mysqld/mysqld.sock --user=root --password=$${MARIADB_ROOT_PASSWORD}
        restartPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
          # NOTE: io_uring is blocked by the default containerd v2 seccomp profile
          # https://github.com/containerd/containerd/pull/9320
          seccompProfile: { type: Unconfined }
      wait-for-mariadb:
        image:
          repository: wait4x/wait4x
          tag: 3.6.0
        args:
          - "mysql"
          - "booklore:$(DB_PASSWORD)@tcp(localhost:3306)/booklore"
        env:
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: mariadb-secret
                key: MARIADB_PASSWORD
    containers:
      booklore:
        image:
          repository: ghcr.io/booklore-app/booklore
          tag: v2.0.6@sha256:fa229a1469b17a44161144655190f27bb9036b909a31584e26ca828c30bd37dd
        command:
          - java
        args:
          - -jar
          - /app/app.jar
        env:
          DATABASE_URL: jdbc:mariadb://localhost:3306/booklore
          DATABASE_USERNAME: booklore
        envFrom:
          - secretRef:
              name: booklore-secret
        probes:
          liveness: &probe
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/healthcheck
                port: &httpPort 6060
          readiness: *probe
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/healthcheck
                port: *httpPort
              failureThreshold: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true

service:
  booklore:
    ports:
      http:
        port: *httpPort

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - booklore.atoca.house
    rules:
      - backendRefs:
          - name: booklore
            port: *httpPort
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    advancedMounts:
      booklore:
        booklore:
          - path: /app/data
            subPath: app
        mariadb:
          - path: /var/lib/mysql
            subPath: mysql
  nfs-nas-media:
    type: nfs
    server: nas.internal
    path: /mnt/user/data
    advancedMounts:
      booklore:
        booklore:
          - path: /books
            subPath: media/books
          - path: /bookdrop
            subPath: torrents/books
  mysqld:
    type: emptyDir
    medium: Memory
    sizeLimit: 1Mi
    advancedMounts:
      booklore:
        mariadb:
          - path: /run/mysqld
  tmpfs:
    type: emptyDir
    medium: Memory
    sizeLimit: 1Mi
    advancedMounts:
      booklore:
        booklore:
          - path: /tmp
            subPath: app
        mariadb:
          - path: /tmp
            subPath: mysql
