---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name python-app-secret
  namespace: python-app
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: python-app
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &dbname python-app-db-secret
  namespace: python-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: *dbname
    creationPolicy: Owner
    template:
      data:
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
        DB_HOST: '{{ index . "pgbouncer-host" }}'
        DB_PORT: '{{ index . "pgbouncer-port" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-python-app
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
