---
replicaCount: 2

image:
  repository: ghcr.io/guilhermewolf/python-app
  tag: 1.0.0

deploymentAnnotations:
  reloader.stakater.com/auto: "true"

config:
  API_BASE_URL: https://python-app.atoca.house
  LOG_LEVEL: INFO

  MAX_CONNECTIONS: "25"

secret:
  existingSecret: python-app-secret

database:
  enabled: true
  existingSecret: python-app-db-secret
  secretKey: DATABASE_URL

postgres:
  enabled: false

service:
  port: 8000

httpRoute:
  enabled: true
  annotations:
    gatus.home-operations.com/endpoint: |-
      path: /livez
      conditions: ["[STATUS] == 200"]
  parentRefs:
    - name: atoca-house-external
      namespace: kube-system
  hostnames:
    - python-app.atoca.house

resources:
  requests:
    cpu: 10m
    memory: 96Mi
  limits:
    memory: 512Mi

podDisruptionBudget:
  enabled: true
  minAvailable: 1
