---
controllers:
  audiobookshelf:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/advplyr/audiobookshelf
          tag: 2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e
        env:
          AUDIOBOOKSHELF_UID: 99
          AUDIOBOOKSHELF_GID: 100
          CONFIG_PATH: /config
          METADATA_PATH: /config/metadata
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthcheck
                port: &port 80
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 1500Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
          readOnlyRootFilesystem: true
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: audiobookshelf
    ports:
      http:
        port: *port
    primary: true

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - audiobookshelf.atoca.house
    rules:
      - backendRefs:
          - name: audiobookshelf
            port: 80
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /config

  cache:
    type: emptyDir
    globalMounts:
      - path: /.npm
  media:
    enabled: true
    type: nfs
    server: nas.internal
    path: /mnt/user/data/
    globalMounts:
      - path: /data
        readOnly: true
  tmpfs:
    type: emptyDir
    globalMounts:
      - path: /tmp
