controllers:
  bazarr:
    replicas: 1
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      bazarr:
        image:
          repository: ghcr.io/home-operations/bazarr
          tag: 1.6.2@sha256:17dc1cff22e99694ffbfb06555526cb47a66b362b4d6c982f06b557f7caae2bb
          pullPolicy: IfNotPresent
        env:
          BAZARR__PORT: &port 6767
        resources:
          requests:
            cpu: 75m
            memory: 320Mi
          limits:
            memory: 1Gi
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/system/ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/system/ping
                port: *port
              initialDelaySeconds: 0
              periodSeconds: 5
              timeoutSeconds: 5
              failureThreshold: 30

defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch
service:
  bazarr:
    controller: bazarr
    ports:
      http:
        port: *port

route:
  bazarr:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - bazarr.atoca.house
    rules:
      - backendRefs:
          - name: bazarr
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  bazarr:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 5Gi
    globalMounts:
      - path: /config

  data:
    enabled: true
    type: nfs
    server: nas.internal
    path: /mnt/user/data
    globalMounts:
      - path: /data
        readOnly: false

  tmp:
    type: emptyDir
