version: '3.8'

services:
  n8n:
    image: n8nio/n8n:1.123.9@sha256:2528c20f9c52d46d02c93519f69f49b3e451c4fa75145e6fd35e6d3805edf258
    container_name: n8n
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Amsterdam
      - WEBHOOK_URL=$WEBHOOK_URL
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 1G
        reservations:
          cpus: "0.5"
          memory: 256M
    volumes:
      - /mnt/blaze/appdata/n8n:/home/node/.n8n
    user: "1000:1000"
    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/tmchow/unraid-docker-templates/master/img/n8n-icon.png"

