---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: envoy-bouncer
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: envoy-bouncer
      app.kubernetes.io/controller: crowdsec-envoy-bouncer
