---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: envoy-bouncer-secrets
  namespace: envoy-bouncer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: envoy-bouncer-secrets
    template:
      data:
        ENVOY_BOUNCER_BOUNCER_APIKEY: "{{ .ENVOY_BOUNCER_BOUNCER_APIKEY }}"
        ENVOY_BOUNCER_WAF_APIKEY: "{{ .ENVOY_BOUNCER_WAF_APIKEY }}"
  dataFrom:
    - extract:
        key: envoy-bouncer-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
