---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: crowdsec-bouncer
  namespace: kube-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: atoca-house-external
  extAuth:
    failOpen: true
    grpc:
      backendRefs:
        - group: ""
          kind: Service
          name: envoy-bouncer
          namespace: envoy-bouncer
          port: 8080
