---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: sonarr
spec:
  sourcePVC: sonarr
  trigger:
    schedule: "0 0 * * *"
  restic:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheStorageClassName: openebs-hostpath
    pruneIntervalDays: 14
    repository: sonarr-r2-secret
    moverSecurityContext:
      runAsUser: 99
      runAsGroup: 100
      fsGroup: 100
    retain:
      hourly: 5
      daily: 4
      monthly: 1
      yearly: 1
    copyMethod: Snapshot
    storageClassName: ceph-block
    volumeSnapshotClassName: csi-ceph-blockpool
