apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memory-mcp
  namespace: mcp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
