apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: shelfmark
  namespace: shelfmark
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: shelfmark
  timeout:
    http:
      requestTimeout: 0s
