app:
  name: rook-ceph-cluster
  namespace: rook-ceph
  chart: rook-ceph-cluster
  chartRepo: https://charts.rook.io/release
  chartVersion: v1.20.2
  disableAutoSync: true
  podSecurityPrivileged: true
