---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-icmp
  annotations:
    avp.kubernetes.io/path: "vaults/K8s/items/ip-address"
spec:
  module: icmp
  prober:
    url: blackbox-exporter-lan.blackbox-exporter-lan.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - <COMPARTILHADO_IP>
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: lan-tcp
  annotations:
    avp.kubernetes.io/path: "vaults/K8s/items/ip-address"
spec:
  module: tcp_connect
  prober:
    url: blackbox-exporter-lan.blackbox-exporter-lan.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - <COMPARTILHADO_IP>:2049
  metricRelabelings:
    - targetLabel: service
      replacement: blackbox-exporter-lan
      action: replace
