---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: atoca-house-tls
  namespace: kube-system
spec:
  secretStoreRefs:
    - name: onepassword-connect
      kind: ClusterSecretStore
  selector:
    secret:
      name: atoca-house-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
    - match:
        secretKey: &key tls.crt
        remoteRef:
          remoteKey: atoca-house-tls
          property: *key
      conversionStrategy: None

    - match:
        secretKey: &key tls.key
        remoteRef:
          remoteKey: atoca-house-tls
          property: *key
      conversionStrategy: None
