---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-pguser-wiki
  namespace: wiki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: wiki-db-secret
    template:
      data:
        DB_HOST: '{{ index . "host" }}'
        DB_NAME: '{{ index . "dbname" }}'
        DB_USER: '{{ index . "user" }}'
        DB_PASS: '{{ index . "password" }}'
        DB_PORT: '{{ index . "port" | toString }}'
        INIT_POSTGRES_HOST: '{{ index . "host" }}'
        INIT_POSTGRES_DBNAME: '{{ index . "dbname" }}'
        INIT_POSTGRES_USER: '{{ index . "user" }}'
        INIT_POSTGRES_PASS: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-wiki
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
