---
controllers:
  ledfx:
    annotations:
      reloader.stakater.com/auto: "true"
    initContainers:
      fix-permissions:
        image:
          repository: docker.io/library/alpine
          tag: "3.24"
        command:
          - sh
          - -c
          - |
            set -euo pipefail

            mkdir -p /home/ledfx/.config/pulse
            mkdir -p /run/ledfx

            chown -R 1000:1000 /home/ledfx/.config/pulse
            chown -R 1000:1000 /run/ledfx

            chmod 700 /home/ledfx/.config/pulse
            chmod 700 /run/ledfx
    containers:
      ledfx:
        image:
          repository: ghcr.io/ledfx/ledfx
          tag: edge
        args:
          - --offline
          - --clear-effects
        env:
          XDG_RUNTIME_DIR: /run/ledfx
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 8888
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 6
          readiness: *probes
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["SYS_NICE"]
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  ledfx:
    controller: ledfx
    ports:
      http:
        port: *port

route:
  ledfx:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - ledfx.atoca.house
    rules:
      - backendRefs:
          - name: ledfx
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /

configMaps:
  pulse-config:
    data:
      default.pa: |
        .nofail
        load-module module-null-sink sink_name=ledfx
        set-default-sink ledfx
        load-module module-native-protocol-unix auth-anonymous=1

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /home/ledfx/ledfx-config

  pulse:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /home/ledfx/.config/pulse

  pulse-run:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /run/ledfx

  pulse-config:
    enabled: true
    type: configMap
    name: ledfx
    globalMounts:
      - path: /etc/pulse/default.pa
        subPath: default.pa
        readOnly: true
