---
#yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperclip-secret
  namespace: paperclip
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        BETTER_AUTH_SECRET: "{{ .BETTER_AUTH_SECRET }}"
        PAPERCLIP_AGENT_JWT_SECRET: "{{ .PAPERCLIP_AGENT_JWT_SECRET }}"
  dataFrom:
    - extract:
        key: paperclip-secrets
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name paperclip-db-secret
  namespace: paperclip
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-postgres-cluster-store
  target:
    name: *name
    template:
      data:
        DATABASE_URL: '{{ index . "pgbouncer-uri" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-paperclip
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
