controllers:
  radarr:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      radarr:
        image:
          repository: ghcr.io/home-operations/radarr
          tag: 6.2.1.10461@sha256:a566e7d364b96ce8ffb1b582266e656c69f3a12dec289d72bb0daa647ed4725e
        env:
          RADARR__APP__INSTANCENAME: Radarr
          RADARR__APP__THEME: dark
          RADARR__LOG__DBENABLED: "False"
          RADARR__LOG__LEVEL: info
          RADARR__SERVER__PORT: &port 80
        envFrom:
          - secretRef:
              name: "radarr-secret"
        probes:
          liveness:
            enabled: true
            spec:
              periodSeconds: 30
              timeoutSeconds: 5
              failureThreshold: 5
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /ping
                port: *port
              periodSeconds: 10
              timeoutSeconds: 5
              failureThreshold: 5
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 3Gi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch
service:
  radarr:
    controller: radarr
    ports:
      http:
        port: *port
route:
  radarr:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - radarr.atoca.house
    rules:
      - backendRefs:
          - name: radarr
            port: 80
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  config:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 3Gi
    globalMounts:
      - path: /config/

  media:
    type: nfs
    server: nas.internal
    path: /mnt/user/data/
    globalMounts:
      - path: /data
  tmp:
    type: emptyDir
