---
controllers:
  ontime:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          # renovate: datasource=docker depName=getontime/ontime
          repository: getontime/ontime
          tag: v4.10.0@sha256:f32ec3c7e6908174a630ba1363ea0a54e3478bf9591fca4feccdb9ee70ba3fc5
        env:
          TZ: Europe/Amsterdam
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 99
    runAsGroup: 100
    fsGroup: 100
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    ports:
      http:
        port: 4001

route:
  app:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: atoca-house-internal
        namespace: kube-system
    hostnames:
      - ontime.atoca.house
    rules:
      - backendRefs:
          - name: ontime
            port: 4001
        matches:
          - path:
              type: PathPrefix
              value: /

persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    storageClass: ceph-block
    accessMode: ReadWriteOnce
    size: 2Gi
    globalMounts:
      - path: /data
