---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-mcp-secret
    creationPolicy: Owner
  data:
    - secretKey: MCP_HTTP_BEARER_TOKEN
      remoteRef:
        key: tailscale-mcp-secret
        property: MCP_HTTP_BEARER_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-oauth-id
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-mcp-oauth-id
    creationPolicy: Owner
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_ID
      remoteRef:
        key: tailscale-mcp-secret
        property: TAILSCALE_OAUTH_CLIENT_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-mcp-oauth-secret
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tailscale-mcp-oauth-secret
    creationPolicy: Owner
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_SECRET
      remoteRef:
        key: tailscale-mcp-secret
        property: TAILSCALE_OAUTH_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
