name: OpenTofu Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**/*.tf'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./infra/terraform

jobs:
  tofu-apply:
    runs-on: arc-runners
    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}
      TF_VAR_zone_id: ${{ secrets.TF_VAR_zone_id }}
      TF_VAR_account_id: ${{ secrets.TF_VAR_account_id }}
      TF_VAR_domain: ${{ secrets.TF_VAR_domain }}
      TF_VAR_npm_ip: ${{ secrets.TF_VAR_npm_ip }}
      TF_VAR_unifi_api_url: ${{ secrets.TF_VAR_unifi_api_url }}
      TF_VAR_unifi_api_key: ${{ secrets.TF_VAR_unifi_api_key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'        

      - uses: opentofu/setup-opentofu@847eaa4afeb791b06daa46e8eafa8b1b68d7cfb4 # v2

      - name: OpenTofu Init
        id: init
        run: tofu init
        
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve
