name: OpenTofu Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**/*.tf'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./infra/terraform

jobs:
  tofu-apply:
    runs-on: arc-runners
    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}
      TF_VAR_zone_id: ${{ secrets.TF_VAR_zone_id }}
      TF_VAR_account_id: ${{ secrets.TF_VAR_account_id }}
      TF_VAR_domain: ${{ secrets.TF_VAR_domain }}
      TF_VAR_npm_ip: ${{ secrets.TF_VAR_npm_ip }}
      TF_VAR_unifi_api_url: ${{ secrets.TF_VAR_unifi_api_url }}
      TF_VAR_unifi_api_key: ${{ secrets.TF_VAR_unifi_api_key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '24'        

      - uses: opentofu/setup-opentofu@a1320f892987e89d278cc92dc5adc984fb93aca4 # v2

      - name: OpenTofu Init
        id: init
        run: tofu init
        
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve
