name: OpenTofu Apply

on:
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**/*.tf'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    working-directory: ./infra/terraform

jobs:
  tofu-apply:
    runs-on: arc-runners
    env:
      TF_VAR_cloudflare_api_token: ${{ secrets.TF_VAR_cloudflare_api_token }}
      TF_VAR_zone_id: ${{ secrets.TF_VAR_zone_id }}
      TF_VAR_account_id: ${{ secrets.TF_VAR_account_id }}
      TF_VAR_domain: ${{ secrets.TF_VAR_domain }}
      TF_VAR_npm_ip: ${{ secrets.TF_VAR_npm_ip }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24'        

      - uses: opentofu/setup-opentofu@fc711fa910b93cba0f3fbecaafc9f42fd0c411cb # v2

      - name: OpenTofu Init
        id: init
        run: tofu init
        
      - name: OpenTofu Apply
        id: apply
        run: tofu apply -auto-approve
