---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deduparr-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: deduparr-secret
    template:
      data:
        DEDUPARR_RADARR_MOVIES_API_KEY: "{{ .RADARR_API_KEY }}"
        DEDUPARR_SONARR_SERIES_API_KEY: "{{ .SONARR_API_KEY }}"
  dataFrom:
    - extract:
        key: radarr-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - extract:
        key: sonarr-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
